export enum ERROR_CODES {
  EINVALIDUSERCREDENTIALS = 'EINVALIDUSERCREDENTIALS',
  EINVALIDCLIENTCREDENTIALS = 'EINVALIDCLIENTCREDENTIALS',
  EAUTHENTICATIONREQUIRED = 'EAUTHENTICATIONREQUIRED',
  EINSUFFICIENTPERMISSIONS = 'EINSUFFICIENTPERMISSIONS',
  ENOTFOUND = 'ENOTFOUND',
  EPAYMENT = 'EPAYMENT',
  ERATELIMITEXCEEDED = 'ERATELIMITEXCEEDED',
  ESERVICEUNAVAILABLE = 'ESERVICEUNAVAILABLE',
  ECONFLICT = 'ECONFLICT',
  ETOKENEXPIRED = 'ETOKENEXPIRED',
  EINVALIDTOKEN = 'EINVALIDTOKEN',
  EVALIDATION = 'EVALIDATION',
  ENOTIMPLEMENTED = 'ENOTIMPLEMENTED',
  EINTERNALSERVER = 'EINTERNALSERVER',
  EINVALIDSIGNATURE = 'EINVALIDSIGNATURE',
  ERELATEDREQUIRED = 'ERELATEDREQUIRED',
  EEMAILVERIFICATION = 'EEMAILVERIFICATION',
  EBADREQUEST = 'EBADREQUEST',
  EUSERNOTREGISTERED = 'EUSERNOTREGISTERED'
}

export enum ATTR_ERR_SOURCE {
  POINTER = 'pointer',
  PARAMETER = 'parameter'
}
